re-add functionality to allow the run_my_cmd function to work properly. add check for the random server gathering. other formatting changes

diff --git a/changeProtonvpnServers b/changeProtonvpnServers
--- a/changeProtonvpnServers
+++ b/changeProtonvpnServers
@@ -7,7 +7,7 @@ fi
 
 function usage() {
   echo "Run the script as follows:"
-  echo "$(basename $0) [-h] [-c country_code] [-vvv] [-l load] [-"
+  echo "$(basename $0) [-h] [-vvv] [-c country_code] [-l load] [-s us_state_abbrev]"
   exit 2
 }
 
@@ -46,17 +46,27 @@ and .value.Load < \"${load}\" \
 and .value.Status == 1 \
 ${server_state}"
 
+function successful_cmd() {
+  successful_cmd="${1}"
+  printf "  ${GREEN}${successful_cmd}\n${NOCOL}"
+}
+
+function failed_cmd() {
+  failed_cmd="${1}"
+  printf "  ${RED}${failed_cmd}\n${NOCOL}"
+  usage
+  exit 1
+}
+
 function run_my_cmd() {
 #  echo "in cmd"
-  cmd="${1}"
-  shift
-  command_attempt=$("${cmd}" "$@")
-  if [[ $? -ne 0 ]]; then
-    printf "${RED}Something went wrong!...${NOCOL}\n"
-    usage
-    exit 1
+  passed_cmd="${@}"
+  ${passed_cmd}
+
+  if [[ $? -eq 0 ]]; then
+    successful_cmd "\n  ${GREEN}Success: ${passed_cmd}${NOCOL}\n"
   else
-    printf "${GREEN}Success...${NOCOL}\n"
+    failed_cmd "\n  ${RED}Something went wrong! Attempted: ${passed_cmd}${NOCOL}\n"
   fi
 }
 
@@ -64,18 +74,26 @@ function run_my_cmd() {
 # not every kind of action can be prepended by the run_my_cmd
 function check_return() {
   if [[ $? -eq 0 ]]; then
-    run_my_cmd /bin/true
+    successful_cmd "${GREEN}Success.${NOCOL}\n"
   else
-    run_my_cmd /bin/false
+    failed_cmd "${RED}Fail.${NOCOL}\n"
   fi
 }
 
 function get_random_server() {
   # get a random index from the list of indexes
   random_server_index=${server_indexes[RANDOM % ${#server_indexes[@]}]}
+
+  if [[ ${#random_server_index[@]} -ne 1 ]]; then
+    failed_cmd "\n Something went wrong setting random_server_index: ${random_server_index}"
+  fi
   # once we have the index, get some info about it
   random_server=$(jq -r ".LogicalServers[${random_server_index}]" ${serverlist})
   random_server_name=$(jq -r ".LogicalServers[${random_server_index}].Name" ${serverlist})
+
+  if [[ ${#random_server_name[@]} -ne 1 ]]; then
+    failed_cmd "\n Somehow we have more than 1 server. Server: ${random_server}, Name: ${random_server_name}"
+  fi
 }
 
 function parse_serverlist() {
@@ -84,8 +102,7 @@ function parse_serverlist() {
 
   # check if the array is populated, otherwise we should fail out at this point
   if [[ ${#server_indexes[@]} -eq 0 ]]; then
-    printf "\n${RED}We didn't find any servers with this search term:\n${NOCOL}${select_this}\n\n"
-    run_my_cmd /bin/false
+    failed_cmd "\nWe didn't find any servers with this search term:\n${NOCOL}${select_this}\n\n"
   fi
 
   if [[ ${verbosity} -ge 3 ]]; then
@@ -107,10 +124,10 @@ function stop_protonvpn() {
     killswitch_connection=$(nmcli c s | awk '/pvpn-killswitch/{print $1}'); check_return
 
     [[ ${verbosity} -ge 1 ]] && printf "${YELLOW}  Stopping networking...${NOCOL}"
-    nmcli networking off; check_return
+    run_my_cmd nmcli networking off
 
     [[ ${verbosity} -ge 1 ]] && printf "${YELLOW}  Removing remnant networking configs...${NOCOL}"
-    killall "${proton_app_command}"; check_return
+    run_my_cmd killall "${proton_app_command}"
   fi
 }
 
@@ -120,7 +137,7 @@ function replace_autoconnect_server() {
 
 function start_protonvpn() {
   [[ ${verbosity} -ge 1 ]] && printf "${YELLOW}  Turning networking back on...${NOCOL}"
-  nmcli networking on; check_return
+  run_my_cmd nmcli networking on
 
   [[ ${verbosity} -ge 1 ]] && printf "${YELLOW}  Starting ${proton_app_command}...${NOCOL}"
   ${proton_app_command} > /dev/null 2>&1 &
@@ -145,13 +162,13 @@ printf "${BLUE}Getting a random server from the array...${NOCOL}"
 get_random_server; check_return
 
 [[ ${verbosity} -ge 1 ]] \
-  && printf "${PURPLE}This is the server we're going to connect to:${NOCOL}\n${random_server}\n"
+  && printf "\n${PURPLE}This is the server we're going to connect to:${NOCOL}\n${random_server}\n"
 
 printf "${BLUE}Stopping ${proton_app_command}...${NOCOL}\n"
-stop_protonvpn; check_return
+stop_protonvpn
 
-printf "${BLUE}Replacing the server with a discovered random one...${NOCOL}\n"
-replace_autoconnect_server; check_return
+printf "${BLUE}Replacing the auto-connect server with a discovered random one...${NOCOL}\n"
+replace_autoconnect_server
 
 printf "${BLUE}Starting ${proton_app_command}...${NOCOL}\n"
-start_protonvpn; check_return
+start_protonvpn
